name: desc_smokescreen
channels:
  - conda-forge
dependencies:
    - python>=3.12
    - numpy
    - ipykernel
    - scipy
    - cosmosis >=2.5
    - astropy >=5.3.0
    - pytest
    - pip
    - numcosmo
    - firecrown>=1.8
    - fitsio
    - pyccl >=3.0.2
    - cryptography
    - pip:
      - argparse
      - flake8
      - sacc
      #- git+https://github.com/LSSTDESC/firecrown.git@master
    - cosmosis-build-standard-library